### ISSUE TITLE
plot_pareto_front for multiple studies

### ISSUE THREAD

**Issue by y0z** [optuna/optunahub-registry#105]
### Motivation

Please implement  the `plot_pareto_front` visualization function for multiple studies.

### Description

Please implement the `plot_pareto_front` visualization function for multiple studies like the figure below (note: it does not need to be exactly the same).
Samples for each study should be colored with a different color to distinguish which samples belong to which study.

<img width="342" alt="image" src="https://github.com/user-attachments/assets/a29ee181-803d-4242-8192-cbd22908d442">

Fig. 4 from https://dl.acm.org/doi/10.1145/3377930.3389817

The following resources may be helpful for you to implement this feature.
- [`plot_pareto_front` for a single study](https://optuna.readthedocs.io/en/stable/reference/visualization/generated/optuna.visualization.plot_pareto_front.html) and [its implementation](https://github.com/optuna/optuna/blob/master/optuna/visualization/_pareto_front.py)
- [Plot Hypervolume History for Multiple Studies](https://hub.optuna.org/visualization/plot_hypervolume_history_multi/)
  - [Its implementation](https://github.com/optuna/optunahub-registry/tree/main/package/visualization/plot_hypervolume_history_multi)
  - [Its pull request](https://github.com/optuna/optunahub-registry/pull/100)

**Comment by hrntsm** [comment]
I am interested in this issue. I will try to implement it.

**Comment by toshihikoyanase** [comment]
@y0z Did #144 resolve this issue?

**Comment by y0z** [comment]
Yes. I close this issue.
