### ISSUE TITLE
A grafted sampler for multi-objective optimization

### ISSUE THREAD

**Issue by eukaryo** [optuna/optunahub-registry#187]
### Motivation

I want to improve sample efficiency of NSGA2.

### Description

My understanding is that the `NSGA2Sampler` generates the first generation (default is 50 trials) using the `RandomSampler`. On the other hand, the `MOTPESampler` also uses the `RandomSampler` for its first 10 trials by default, but often finds a diverse set of good `params` within the following 40 trials. So, there can be a strategy that the first 50 trials to the `MOTPESampler` and then transfer to the `NSGA2Sampler` for the 51st trial and onwards.

It's worth noting that `NSGA2Sampler` sets some `system_attr` on the study and trials, so implementing the strategy correctly may not be a straightforward process.

**Comment by nabenabe0928** [comment]
I think you can do like this:

```python
class NSGAIIAfterTPESampler(NSGAIISampler):
    def sample_relative(
        self,
        study: Study,
        trial: FrozenTrial,
        search_space: dict[str, BaseDistribution],
    ) -> dict[str, Any]:
        if trial.number < self._population_size:
            sampler = TPESampler(...)
            study._storage.set_trial_system_attr(trial._trial_id, _GENERATION_KEY, 0)
             return sampler.sample_relative(study, trial, search_space)

        return super().sample_relative(study, trial, search_space)

```
